# Generated by Django 2.0 on 2018-11-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idt', models.CharField(max_length=10, unique=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=25, verbose_name='Marca')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fechaIngreso', models.DateField()),
                ('descripcion', models.TextField(max_length=30)),
            ],
        ),
    ]
